[versions]
kotlin-gradlePlugin = "2.3.21"
compose-gradlePlugin = "1.11.0"
download-gradlePlugin = "5.7.0"
java = "25"
gradle = "9.5.1"
junit = "6.1.0"
assertj = "3.27.7"
systemStubs = "2.1.8"
buildConfig = "6.0.9"
mavenPublish = "0.36.0"
gradlePublish = "2.1.1"

[libraries]
# Can find the id of a Gradle plugin as described in https://stackoverflow.com/q/74221701
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-gradlePlugin" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-gradlePlugin" }
download-gradlePlugin = { group = "de.undercouch.download", name = "de.undercouch.download.gradle.plugin", version.ref = "download-gradlePlugin" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
systemStubs-core = { group = "uk.org.webcompere", name = "system-stubs-core", version.ref = "systemStubs" }
systemStubs-jupiter = { group = "uk.org.webcompere", name = "system-stubs-jupiter", version.ref = "systemStubs" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-gradlePlugin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
gradlePublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
